flight=str(input('номер рейса: '))
airline_rus=str(input('название авиакомпании (на русском языке): '))
airline_eng=str(input('название авиакомпании (на английском языке языке): '))
arrival_city_rus=str(input('город прилета (на русском языке): '))
arrival_city_eng=str(input('город прилета (на английском языке): '))
print('Заканчивается посадка на рейс', flight, airline_rus, 'до', arrival_city_rus)
print('This is the final boarding call for', airline_eng, 'flight', flight, 'to', arrival_city_eng)
